version: build{build}
image: Visual Studio 2015
configuration: Release
platform: x64
  
environment:
  matrix:
    - TEST_INTERVAL_LIB: "gaol"
      MSYS_BASE_LIB: C:\MinGW\msys\1.0\lib
      MSYS_BASE_BIN: C:\MinGW\msys\1.0\bin
      MSYS_BASE_INCLUDE: C:\MinGW\msys\1.0\include
      MINGW_BASE_BIN: C:\MinGW\bin
      MINGW_BASE_LIB: C:\MinGW\lib
      MINGW_BASE_INCLUDE: C:\MinGW\include      
    - TEST_INTERVAL_LIB: "filib"
      MSYS_BASE_LIB: C:\MinGW\msys\1.0\lib
      MSYS_BASE_BIN: C:\MinGW\msys\1.0\bin
      MSYS_BASE_INCLUDE: C:\MinGW\msys\1.0\include
      MINGW_BASE_BIN: C:\MinGW\bin
      MINGW_BASE_LIB: C:\MinGW\lib
      MINGW_BASE_INCLUDE: C:\MinGW\include  
    - TEST_INTERVAL_LIB: "filib" 
      MSYS_BASE_LIB: C:\msys64\mingw32\lib
      MSYS_BASE_BIN: C:\msys64\usr\bin;C:\msys64\mingw32\bin
      MSYS_BASE_INCLUDE: C:\msys64\mingw32\include
      MINGW_BASE_BIN: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw32\bin
      MINGW_BASE_LIB: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw32\lib
      MINGW_BASE_INCLUDE: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw32\include  

install:
  - cmd: echo %Platform%
 # - cmd: set MINGW-W64_BASE=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0 
 # - cmd: set MINGW-W64_BASE=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1
  - cmd: uname -a
  - cmd: mkdir C:\ibex
  - cmd: set PATH=%PATH%;%MINGW_BASE_BIN%;%MSYS_BASE_BIN%
  - cmd: set CPATH=%CPATH%;%MINGW_BASE_INCLUDE%;%MSYS_BASE_INCLUDE%
  - cmd: set LIBRARY_PATH=%LIBRARY_PATH%;%MINGW_BASE_LIB%;%MSYS_BASE_LIB%
 # - cmd: pacman --noconfirm -S mingw-w64-i686-cppunit
 # - cmd: pacman --noconfirm -S mingw-w64-i686-lapack
  - cmd: set PREFIX=C:\projects\ibex
  

build_script:
  - cmd: python -x waf configure --interval-lib=%TEST_INTERVAL_LIB% --prefix=%PREFIX% --with-debug --with-ampl --with-optim  --lp-lib=clp
  - cmd: python -x waf install

test_script:
  - cmd: set PKG_CONFIG_PATH=%PREFIX%\share\pkgconfig
  # We need to add the path to libcppunit in PATH
 # - cmd: set PATH=%PATH%;C:\msys64\mingw32\bin
  - cmd: python -x waf utest

on_failure:
  - cmd: cat __build__\config.log
  - cmd: cat __build__\utest_config.log
  - cmd: cat __build__\utest_run.log
